language: csharp
solution: ./src/BOG.SwissArmyKnife.sln
dotnet: 3.1
script:
- dotnet build -c debug ./src/BOG.SwissArmyKnife.sln
- dotnet test src/BOG.SwissArmyKnife.Test/BOG.SwissArmyKnife.Test.csproj --no-build -v normal
- dotnet nuget ./src/BOG.SwissArmyKnife/bin/debug/BOG.SwissArmyKnife.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE --skip-duplicate
