language: csharp
solution: ./src/BOG.SwissArmyKnife.sln
dotnet: 3.1
mono: latest
install:
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
- dotnet build -c release ./src/BOG.SwissArmyKnife.sln
- dotnet test src/BOG.SwissArmyKnife.Test/BOG.SwissArmyKnife.Test.csproj --no-build -v normal
- dotnet nuget ./src/BOG.SwissArmyKnife/bin/Release/BOG.SwissArmyKnife.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE --skip-duplicate
