using System;
using System.Collections.Generic;
using System.Text;

namespace BOG.SwissArmyKnife.Demo.Support
{
    public class PhraseGenerator
    {
        Random r;
        // chizzled from web sites to gain a list of test words.
        string[] adjective = new string[] {
                "abandoned","able","absolute","adorable","adventurous","academic","acceptable","acclaimed","accomplished","accurate","aching","acidic","acrobatic","active","actual",
                "adept","admirable","admired","adolescent","adorable","adored","advanced","afraid","affectionate","aged","aggravating","aggressive","agile","agitated","agonizing",
                "agreeable","ajar","alarmed","alarming","alert","alienated","alive","all","altruistic","amazing","ambitious","ample","amused","amusing","anchored",
                "ancient","angelic","angry","anguished","animated","annual","another","antique","anxious","any","apprehensive","appropriate","apt","arctic","arid",
                "aromatic","artistic","ashamed","assured","astonishing","athletic","attached","attentive","attractive","austere","authentic","authorized","automatic","avaricious","average",
                "aware","awesome","awful","awkward","babyish","bad","back","baggy","bare","barren","basic","beautiful","belated","beloved","beneficial",
                "better","best","bewitched","big","big-hearted","biodegradable","bite-sized","bitter","black","black-and-white","bland","blank","blaring","bleak","blind",
                "blissful","blond","blue","blushing","bogus","boiling","bold","bony","boring","bossy","both","bouncy","bountiful","bowed","brave",
                "breakable","brief","bright","brilliant","brisk","broken","bronze","brown","bruised","bubbly","bulky","bumpy","buoyant","burdensome","burly",
                "bustling","busy","buttery","buzzing","calculating","calm","candid","canine","capital","carefree","careful","careless","caring","cautious","cavernous",
                "celebrated","charming","cheap","cheerful","cheery","chief","chilly","chubby","circular","classic","clean","clear","clear-cut","clever","close",
                "closed","cloudy","clueless","clumsy","cluttered","coarse","cold","colorful","colorless","colossal","comfortable","common","compassionate","competent","complete",
                "complex","complicated","composed","concerned","concrete","confused","conscious","considerate","constant","content","conventional","cooked","cool","cooperative","coordinated",
                "corny","corrupt","costly","courageous","courteous","crafty","crazy","creamy","creative","creepy","criminal","crisp","critical","crooked","crowded",
                "cruel","crushing","cuddly","cultivated","cultured","cumbersome","curly","curvy","cute","cylindrical","damaged","damp","dangerous","dapper","daring",
                "darling","dark","dazzling","dead","deadly","deafening","dear","dearest","decent","decimal","decisive","deep","defenseless","defensive","defiant",
                "deficient","definite","definitive","delayed","delectable","delicious","delightful","delirious","demanding","dense","dental","dependable","dependent","descriptive","deserted",
                "detailed","determined","devoted","different","difficult","digital","diligent","dim","dimpled","dimwitted","direct","disastrous","discrete","disfigured","disgusting",
                "disloyal","dismal","distant","downright","dreary","dirty","disguised","dishonest","dismal","distant","distinct","distorted","dizzy","dopey","doting ",
                "double","downright","drab","drafty","dramatic","dreary","droopy","dry","dual","dull","dutiful","each","eager","earnest","early",
                "easy","easy-going","ecstatic","edible","educated","elaborate","elastic","elated","elderly","electric","elegant","elementary","elliptical","embarrassed","embellished",
                "eminent","emotional","empty","enchanted","enchanting","energetic","enlightened","enormous","enraged","entire","envious","equal","equatorial","essential","esteemed",
                "ethical","euphoric","even","evergreen","everlasting","every","evil","exalted","excellent","exemplary","exhausted","excitable","excited","exciting","exotic",
                "expensive","experienced","expert","extraneous","extroverted","extra-large","extra-small","fabulous","failing","faint","fair","faithful","fake","false","familiar",
                "famous","fancy","fantastic","far","faraway","far-flung","far-off","fast","fat","fatal","fatherly","favorable","favorite","fearful","fearless",
                "feisty","feline","female","feminine","few","fickle","filthy","fine","finished","firm","first","firsthand","fitting","fixed","flaky",
                "flamboyant","flashy","flat","flawed","flawless","flickering","flimsy","flippant","flowery","fluffy","fluid","flustered","focused","fond","foolhardy",
                "foolish","forceful","forked","formal","forsaken","forthright","fortunate","fragrant","frail","frank","frayed","free","French","fresh","frequent",
                "friendly","frightened","frightening","frigid","frilly","frizzy","frivolous","front","frosty","frozen","frugal","fruitful","full","fumbling","functional",
                "funny","fussy","fuzzy","gargantuan","gaseous","general","generous","gentle","genuine","giant","giddy","gigantic","gifted","giving","glamorous",
                "glaring","glass","gleaming","gleeful","glistening","glittering","gloomy","glorious","glossy","glum","golden","good","good-natured","gorgeous","graceful",
                "gracious","grand","grandiose","granular","grateful","grave","gray","great","greedy","green","gregarious","grim","grimy","gripping","grizzled",
                "gross","grotesque","grouchy","grounded","growing","growling","grown","grubby","gruesome","grumpy","guilty","gullible","gummy","hairy","half",
                "handmade","handsome","handy","happy","happy-go-lucky","hard","hard-to-find","harmful","harmless","harmonious","harsh","hasty","hateful","haunting","healthy",
                "heartfelt","hearty","heavenly","heavy","hefty","helpful","helpless","hidden","hideous","high","high-level","hilarious","hoarse","hollow","homely",
                "honest","honorable","honored","hopeful","horrible","hospitable","hot","huge","humble","humiliating","humming","humongous","hungry","hurtful","husky",
                "icky","icy","ideal","idealistic","identical","idle","idiotic","idolized","ignorant","ill","illegal","ill-fated","ill-informed","illiterate","illustrious",
                "imaginary","imaginative","immaculate","immaterial","immediate","immense","impassioned","impeccable","impartial","imperfect","imperturbable","impish","impolite","important","impossible",
                "impractical","impressionable","impressive","improbable","impure","inborn","incomparable","incompatible","incomplete","inconsequential","incredible","indelible","inexperienced","indolent","infamous",
                "infantile","infatuated","inferior","infinite","informal","innocent","insecure","insidious","insignificant","insistent","instructive","insubstantial","intelligent","intent","intentional",
                "interesting","internal","international","intrepid","ironclad","irresponsible","irritating","itchy","jaded","jagged","jam-packed","jaunty","jealous","jittery","joint",
                "jolly","jovial","joyful","joyous","jubilant","judicious","juicy","jumbo","junior","jumpy","juvenile","kaleidoscopic","keen","key","kind",
                "kindhearted","kindly","klutzy","knobby","knotty","knowledgeable","knowing","known","kooky","kosher","lame","lanky","large","last","lasting",
                "late","lavish","lawful","lazy","leading","lean","leafy","left","legal","legitimate","light","lighthearted","likable","likely","limited",
                "limp","limping","linear","lined","liquid","little","live","lively","livid","loathsome","lone","lonely","long","long-term","loose",
                "lopsided","lost","loud","lovable","lovely","loving","low","loyal","lucky","lumbering","luminous","lumpy","lustrous","luxurious","mad",
                "made-up","magnificent","majestic","major","male","mammoth","married","marvelous","masculine","massive","mature","meager","mealy","mean","measly",
                "meaty","medical","mediocre","medium","meek","mellow","melodic","memorable","menacing","merry","messy","metallic","mild","milky","mindless",
                "miniature","minor","minty","miserable","miserly","misguided","misty","mixed","modern","modest","moist","monstrous","monthly","monumental","moral",
                "mortified","motherly","motionless","mountainous","muddy","muffled","multicolored","mundane","murky","mushy","musty","muted","mysterious","naive","narrow",
                "nasty","natural","naughty","nautical","near","neat","necessary","needy","negative","neglected","negligible","neighboring","nervous","new","next",
                "nice","nifty","nimble","nippy","nocturnal","noisy","nonstop","normal","notable","noted","noteworthy","novel","noxious","numb","nutritious",
                "nutty","obedient","obese","oblong","oily","oblong","obvious","occasional","odd","oddball","offbeat","offensive","official","old","old-fashioned",
                "only","open","optimal","optimistic","opulent","orange","orderly","organic","ornate","ornery","ordinary","original","other","our","outlying",
                "outgoing","outlandish","outrageous","outstanding","oval","overcooked","overdue","overjoyed","overlooked","palatable","pale","paltry","parallel","parched","partial",
                "passionate","past","pastel","peaceful","peppery","perfect","perfumed","periodic","perky","personal","pertinent","pesky","pessimistic","petty","phony",
                "physical","piercing","pink","pitiful","plain","plaintive","plastic","playful","pleasant","pleased","pleasing","plump","plush","polished","polite",
                "political","pointed","pointless","poised","poor","popular","portly","posh","positive","possible","potable","powerful","powerless","practical","precious",
                "present","prestigious","pretty","precious","previous","pricey","prickly","primary","prime","pristine","private","prize","probable","productive","profitable",
                "profuse","proper","proud","prudent","punctual","pungent","puny","pure","purple","pushy","putrid","puzzled","puzzling","quaint","qualified",
                "quarrelsome","quarterly","queasy","querulous","questionable","quick","quick-witted","quiet","quintessential","quirky","quixotic","quizzical","radiant","ragged","rapid",
                "rare","rash","raw","recent","reckless","rectangular","ready","real","realistic","reasonable","red","reflecting","regal","regular","reliable",
                "relieved","remarkable","remorseful","remote","repentant","required","respectful","responsible","repulsive","revolving","rewarding","rich","rigid","right","ringed",
                "ripe","roasted","robust","rosy","rotating","rotten","rough","round","rowdy","royal","rubbery","rundown","ruddy","rude","runny",
                "rural","rusty","sad","safe","salty","same","sandy","sane","sarcastic","sardonic","satisfied","scaly","scarce","scared","scary",
                "scented","scholarly","scientific","scornful","scratchy","scrawny","second","secondary","second-hand","secret","self-assured","self-reliant","selfish","sentimental","separate",
                "serene","serious","serpentine","several","severe","shabby","shadowy","shady","shallow","shameful","shameless","sharp","shimmering","shiny","shocked",
                "shocking","shoddy","short","short-term","showy","shrill","shy","sick","silent","silky","silly","silver","similar","simple","simplistic",
                "sinful","single","sizzling","skeletal","skinny","sleepy","slight","slim","slimy","slippery","slow","slushy","small","smart","smoggy",
                "smooth","smug","snappy","snarling","sneaky","sniveling","snoopy","sociable","soft","soggy","solid","somber","some","spherical","sophisticated",
                "sore","sorrowful","soulful","soupy","sour","Spanish","sparkling","sparse","specific","spectacular","speedy","spicy","spiffy","spirited","spiteful",
                "splendid","spotless","spotted","spry","square","squeaky","squiggly","stable","staid","stained","stale","standard","starchy","stark","starry",
                "steep","sticky","stiff","stimulating","stingy","stormy","straight","strange","steel","strict","strident","striking","striped","strong","studious",
                "stunning","stupendous","stupid","sturdy","stylish","subdued","submissive","substantial","subtle","suburban","sudden","sugary","sunny","super","superb",
                "superficial","superior","supportive","sure-footed","surprised","suspicious","svelte","sweaty","sweet","sweltering","swift","sympathetic","tall","talkative","tame",
                "tan","tangible","tart","tasty","tattered","taut","tedious","teeming","tempting","tender","tense","tepid","terrible","terrific","testy",
                "thankful","that","these","thick","thin","third","thirsty","this","thorough","thorny","those","thoughtful","threadbare","thrifty","thunderous",
                "tidy","tight","timely","tinted","tiny","tired","torn","total","tough","traumatic","treasured","tremendous","tragic","trained","tremendous",
                "triangular","tricky","trifling","trim","trivial","troubled","true","trusting","trustworthy","trusty","truthful","tubby","turbulent","twin","ugly",
                "ultimate","unacceptable","unaware","uncomfortable","uncommon","unconscious","understated","unequaled","uneven","unfinished","unfit","unfolded","unfortunate","unhappy","unhealthy",
                "uniform","unimportant","unique","united","unkempt","unknown","unlawful","unlined","unlucky","unnatural","unpleasant","unrealistic","unripe","unruly","unselfish",
                "unsightly","unsteady","unsung","untidy","untimely","untried","untrue","unused","unusual","unwelcome","unwieldy","unwilling","unwitting","unwritten","upbeat",
                "upright","upset","urban","usable","used","useful","useless","utilized","utter","vacant","vague","vain","valid","valuable","vapid",
                "variable","vast","velvety","venerated","vengeful","verifiable","vibrant","vicious","victorious","vigilant","vigorous","villainous","violet","violent","virtual",
                "virtuous","visible","vital","vivacious","vivid","voluminous","wan","warlike","warm","warmhearted","warped","wary","wasteful","watchful","waterlogged",
                "watery","wavy","wealthy","weak","weary","webbed","wee","weekly","weepy","weighty","weird","welcome","well-documented","well-groomed","well-informed",
                "well-lit","well-made","well-off","well-to-do","well-worn","wet","which","whimsical","whirlwind","whispered","white","whole","whopping","wicked","wide",
                "wide-eyed","wiggly","wild","willing","wilted","winding","windy","winged","wiry","wise","witty","wobbly","woeful","wonderful","wooden",
                "woozy","wordy","worldly","worn","worried","worrisome","worse","worst","worthless","worthwhile","worthy","wrathful","wretched","writhing","wrong"
            };
        string[] noun = new string[] {
                "ball","bat","bed","book","boy","bun","can","cake","cap","car","cat","cow","cub","cup","dad",
                "day","dog","doll","dust","fan","feet","girl","gun","hall","hat","hen","jar","kite","man","map",
                "men","mom","pan","pet","pie","pig","pot","rat","son","sun","toe","tub","apple","arm","banana",
                "bike","bird","book","chin","clam","class","clover","club","corn","crayon","crow","crown","crowd","crib","desk",
                "dime","dirt","dress","field","flag","flower","fog","game","heat","hill","home","horn","hose","joke","juice",
                "kite","lake","maid","mask","mice","milk","mint","meal","meat","moon","mother","morning","name","nest","nose",
                "pear","pen","pencil","plant","rain","river","road","rock","room","rose","seed","shape","shoe","shop","show",
                "sink","snail","snake","snow","soda","sofa","star","step","stew","stove","straw","string","summer","swing","table",
                "tank","team","tent","test","toes","tree","vest","water","wing","winter","woman","alarm","animal","aunt","bait",
                "balloon","bath","bead","beam","bean","bedroom","boot","bread","brick","brother","camp","chicken","children","crook","deer",
                "dock","doctor","downtown","drum","dust","eye","family","father","fight","flesh","food","frog","goose","grade","grandfather",
                "grandmother","grape","grass","hook","horse","jail","jam","kiss","kitten","light","loaf","lock","lunch","lunchroom","meal",
                "mother","notebook","owl","pail","parent","park","plot","rabbit","rake","robin","sack","sail","scale","sea","sister",
                "soap","song","spark","space","spoon","spot","spy","summer","tiger","toad","town","trail","tramp","tray","trick",
                "trip","uncle","vase","winter","water","week","wheel","wish","wool","yard","actor","airplane","airport","army","baseball",
                "beef","birthday","boy","brush","bushes","cast","cave","cent","cherries","cherry","cobweb","coil","cracker","dinner","eggnog",
                "elbow","face","fireman","flavor","gate","glove","glue","goldfish","goose","grain","hair","haircut","hobbies","holiday","hot",
                "jellyfish","ladybug","mailbox","number","oatmeal","pail","pancake","pear","pest","popcorn","queen","quicksand","quiet","quilt","rainstorm",
                "scarecrow","scarf","stream","street","sugar","throne","toothpaste","twig","volleyball","wood","advice","anger","answer","apple","arithmetic",
                "badge","basket","basketball","battle","beast","beetle","beggar","brain","branch","bubble","bucket","cactus","cannon","cattle","celery",
                "cellar","cloth","coach","coast","crate","cream","daughter","donkey","drug","earthquake","feast","fifth","finger","flock","frame",
                "furniture","geese","ghost","giraffe","governor","honey","hope","hydrant","icicle","income","island","jeans","judge","lace","lamp",
                "lettuce","marble","month","north","ocean","patch","plane","playground","poison","riddle","rifle","scale","seashore","sheet","sidewalk",
                "skate","slave","sleet","smoke","stage","station","thrill","throat","throne","title","toothbrush","turkey","underwear","vacation","vegetable",
                "visitor","voyage","able","achieve","acoustics","action","activity","aftermath","afternoon","afterthought","apparel","appliance","beginner","believe","bomb",
                "border","boundary","breakfast","cabbage","cable","calculator","calendar","caption","carpenter","cemetery","channel","circle","creator","creature","education",
                "faucet","feather","friction","fruit","fuel","galley","guide","guitar","health","heart","idea","kitten","laborer","language","lawyer",
                "linen","locket","lumber","magic","minister","mitten","money","mountain","music","partner","passenger","pickle","picture","plantation","plastic",
                "pleasure","pocket","police","pollution","railway","recess","reward","route","scene","scent","squirrel","stranger","suit","sweater","temper",
                "territory","texture","thread","treatment","veil","vein","volcano","wealth","weather","wilderness","wren","wrist","account","achiever",
                "acoustics","act","action","activity","actor","addition","adjustment","advertisement","advice","aftermath","afternoon","afterthought","agreement","air","airplane",
                "airport","alarm","amount","amusement","anger","angle","answer","ant","apparatus","apparel","apple","appliance","approval","arch","argument",
                "arithmetic","arm","army","art","attack","attempt","attention","attraction","aunt","B","back","badge","bag","bait","balance",
                "ball","balloon","banana","band","base","baseball","basin","basket","basketball","bat","bath","battle","bead","beam","bean",
                "bear","beast","bed","bedroom","bee","beef","beetle","beggar","beginner","behavior","belief","believe","bell","berry","bike",
                "bird","birth","birthday","bit","bite","blade","blood","blow","board","boat","body","bomb","bone","book","boot",
                "border","bottle","boundary","box","boy","brain","brake","branch","brass","bread","breakfast","breath","brick","bridge","brother",
                "brush","bubble","bucket","building","bulb","bun","burn","burst","bushes","business","butter","C","cabbage","cable","cactus",
                "cake","calculator","calendar","camera","camp","can","cannon","canvas","cap","caption","card","care","carpenter","carriage","cart",
                "cast","cat","cattle","cause","cave","celery","cellar","cemetery","cent","chain","chalk","chance","change","channel","cheese",
                "cherries","cherry","chess","children","chin","church","circle","clam","class","clock","cloth","cloud","clover","club","coach",
                "coal","coast","coat","cobweb","coil","collar","color","comb","comfort","committee","company","comparison","competition","condition","connection",
                "control","cook","copper","copy","cord","cork","cough","country","cover","cow","crack","cracker","crate","crayon","cream",
                "creator","creature","credit","crib","crime","crook","crow","crowd","crown","crush","cry","cub","cup","current","curtain",
                "curve","D","dad","daughter","day","death","debt","decision","deer","degree","design","desire","desk","destruction","detail",
                "development","digestion","dime","dinner","direction","dirt","discovery","discussion","disease","disgust","distance","distribution","division","dock","doctor",
                "dog","doll","donkey","door","downtown","drain","drawer","dress","drink","driving","drop","drug","drum","E","ear",
                "earth","earthquake","edge","education","effect","egg","eggnog","elbow","end","engine","error","event","example","exchange","existence",
                "expansion","experience","expert","eye","F","face","fact","fall","family","fan","farm","father","father","faucet","fear",
                "feast","feather","feeling","feet","fiction","field","fifth","fight","finger","finger","fireman","fish","flag","flame","flavor",
                "flesh","flight","flock","floor","flower","fly","fog","fold","food","foot","force","fork","form","fowl","frame",
                "friction","friend","frog","front","fruit","fuel","G","alley","game","garden","gate","geese","ghost","giraffe","girl",
                "glass","glove","glue","goat","gold","goldfish","goose","government","governor","grade","grain","grandfather","grandmother","grape","grass",
                "grip","ground","group","growth","guide","guitar","H","hair","haircut","hall","hammer","hand","harbor","harmony","hat",
                "hate","head","health","hearing","heart","heat","help","hen","history","hobbies","hole","holiday","honey","hook","hope",
                "horn","horse","hose","hospital","hot","hour","house","humor","I","ice","icicle","idea","impulse","income","increase",
                "industry","ink","insect","instrument","insurance","interest","invention","iron","J","jail","jam","jar","jeans","jelly","jellyfish",
                "jewel","join","joke","journey","judge","juice","K","kettle","key","kick","kiss","kite","kitten","knee","knife",
                "knot","L","laborer","lace","ladybug","lake","lamp","land","language","laugh","lawyer","lead","leaf","learning","leather",
                "legs","letter","lettuce","level","library","lift","light","limit","line","linen","lip","liquid","list","loaf","lock",
                "locket","look","loss","love","low","lumber","lunch","M","machine","magic","maid","mailbox","man","manager","map",
                "marble","mark","market","mask","mass","match","meal","measure","meat","meeting","memory","men","metal","middle","milk",
                "mind","mine","minister","mint","minute","mist","mitten","mom","money","monkey","month","moon","morning","mother","motion",
                "mountain","mouth","move","muscle","N","nail","name","nation","neck","need","needle","nerve","net","news","night",
                "noise","north","nose","note","notebook","number","O","oatmeal","observation","ocean","offer","office","oil","operation","opinion",
                "orange","order","organization","ornament","oven","owl","P","page","pail","pain","paint","pan","pancake","paper","parcel",
                "parent","park","part","partner","party","passenger","paste","patch","payment","peace","pear","pen","pencil","person","pest",
                "pet","pickle","picture","pie","pig","pin","pipe","place","plane","plant","plantation","plastic","plate","play","playground",
                "pleasure","plot","plough","pocket","point","poison","police","polish","pollution","popcorn","porter","position","pot","potato","powder",
                "power","price","print","prison","process","produce","profit","property","prose","protest","pull","pump","punishment","purpose","Q",
                "quarter","quartz","queen","question","quicksand","quiet","quill","quilt","quince","R","rail","railway","rain","rainstorm","rake",
                "range","rat","rate","ray","reaction","reading","reason","receipt","recess","record","regret","relation","religion","representative","request",
                "respect","rest","reward","rhythm","rice","riddle","rifle","ring","river","road","rock","rod","roll","roof","room",
                "root","rose","route","rub","rule","S","sack","sail","salt","sand","scale","scarecrow","scarf","scene","scent",
                "school","science","scissors","screw","sea","seashore","seat","secretary","seed","selection","self","sense","servant","shade","shake",
                "shame","shape","sheep","sheet","shelf","ship","shirt","shock","shoe","shop","show","side","sidewalk","sign","silk",
                "silver","sink","sister","size","skate","skin","skirt","sky","slave","sleep","sleet","slip","slope","smash","smell",
                "smile","smoke","snail","snake","sneeze","snow","soap","society","sock","soda","sofa","son","song","sort","sound",
                "soup","space","spade","spark","sponge","spoon","spot","spring","spy","square","squirrel","stage","stamp","star","start",
                "statement","station","steam","steel","stem","step","stew","stick","stitch","stocking","stomach","stone","stop","store","story",
                "stove","stranger","straw","stream","street","stretch","string","structure","substance","sugar","suggestion","suit","summer","sun","support",
                "surprise","sweater","swim","swing","T","table","tail","talk","tank","taste","tax","teaching","team","temper","tendency",
                "tent","territory","test","texture","theory","thing","thought","thread","thrill","throat","throne","thumb","thunder","ticket","tiger",
                "time","tin","title","toad","toe","toes","tongue","tooth","toothbrush","toothpaste","touch","town","trade","trail","train",
                "tramp","transport","tray","treatment","tree","trick","trip","trouble","trousers","truck","tub","turkey","turn","twig"
            };

        public PhraseGenerator()
        {
            r = new Random(DateTime.Now.Millisecond);
        }

        public List<string> GetPhrase(int count)
        {
            List<string> result = new List<string>();
            for (int index = 0; index < count; index++)
                result.Add(adjective[r.Next(adjective.Length)] + " " + noun[r.Next(noun.Length)]);
            return result;
        }
    }
}
