# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop", "release", "master" ]

defaults:
  run:
    working-directory: src/BOG.SwissArmyKnife

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.200
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
	  env:
	    BUILD_CONFIG: $({ github.ref == 'refs/heads/develop' ? 'debug' : 'release' }) 
	    BUILD_DIR: $({ github.ref == 'refs/heads/develop' ? 'Debug' : 'Release' }) 
      run: dotnet build --no-restore -c ${BUILD_CONFIG} BOG.SwissArmyKnife.csproj
    - name: NuGet Push
	  env:
	    NGKEY: ${{ secrets.NUGET_API_KEY }}
	  if: $({ github.ref == 'refs/heads/master' }) && $({ NUGET_SOURCE != null }) && $({ env.NGKEY != null })
	  run: dotnet nuget push ./bin/${BUILD_DIR}/BOG.SwissArmyKnife.*.nupkg --api-key ${NGKEY} --source $NUGET_SOURCE --skip-duplicate
